---

- name: Check if task is working
  shell: hostname -f
  register: full_hostname

- debug: var=full_hostname.stdout_lines

- name: Create Vagrant directories
  file:
    path: "{{ vagrant_dir }}/{{ item.key }}"
    state: directory
  with_dict: "{{ node_directories }}"

- name: Apply Vagrant template
  template:
    src: Vagrantfile.j2
    dest: "{{ vagrant_dir }}/{{ item.key }}/Vagrantfile"
  vars:
    - group_vars_ip: "{{ item.value.ip }}"
  with_dict: "{{ node_directories }}"

- name: Apply restart-sshd.sh template
  template:
    src: restart-sshd.sh.j2
    dest: "{{ vagrant_dir }}/{{ item.key }}/restart-sshd.sh"
  with_dict: "{{ node_directories }}"

- name: vagrant up
  shell: "cd {{ vagrant_dir }}/{{ item.key }} && vagrant up"
  register: vagrant_up
  with_dict: "{{ node_directories }}"

- name: restart sshd with modified configuration
  shell: "cd {{ vagrant_dir }}/{{ item.key }} && vagrant ssh -c 'sudo chmod 755 /vagrant/restart-sshd.sh && sudo /vagrant/restart-sshd.sh '"
  with_dict: "{{ node_directories }}"

- name: delete lines from /Users/XXXXX.bae/.ssh/known_hosts when it matches 192.168.33.*
  shell: "sed -i '' '/{{c_class_ip}}/d' ~/.ssh/known_hosts"

