---
# Download and install EPEL for Centos/RHEL version 6
- name: Download EPEL Repo - Centos/RHEL 6
  get_url: url=http://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm dest=/tmp/epel-release-latest-6.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

- name: Install EPEL Repo - Centos/RHEL 6
  command: rpm -ivh /tmp/epel-release-latest-6.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'"

# Download and install EPEL for Centos/RHEL version 7
- name: Download EPEL Repo - Centos/RHEL 7
  get_url: url=http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm dest=/tmp/epel-release-latest-7.noarch.rpm
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install EPEL Repo - Centos/RHEL 7
  command: rpm -ivh /tmp/epel-release-latest-7.noarch.rpm creates=/etc/yum.repos.d/epel.repo
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install libselinux-python
  yum: name=libselinux-python

- name: Install MySQL-python
  yum: name=MySQL-python

- name: Install Pecona Repository
  yum: name=http://www.percona.com/downloads/percona-release/redhat/0.1-4/percona-release-0.1-4.noarch.rpm

- name: Install Pecona
  yum: name={{ item }} state=latest
  with_items:
    - percona-toolkit.x86_64 
    - percona-xtrabackup-24.x86_64 
    - qpress.x86_64
  become: yes

- name: Install extra package
  yum: name={{ item }} state=latest
  with_items:
    - vim 
    - screen
  become: yes

- name: Deploy neccessary files to the target hosts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
  with_items:
    - {src: 'sysbench', dest: '/usr/bin/', mode: '755'}
